---
  - hosts: dev
 #   connection: local
    gather_facts: no
  #  become: true
    gather_facts: true
    roles:
      - { role: centos, when: ansible_distribution == "CentOS" }
      - { role: rhel, when: ansible_distribution == "RedHat" }
